### ISSUE TITLE
Remove build number from release artifacts.

### ISSUE THREAD

**Issue by estenrye** [platform9/nodelet#59]
The build process for nodelet produces artifacts whose filename contains an incrementing build number.

This impacts the ability to reliably automate deployment based on the release version tag alone.

Current state:
- https://github.com/platform9/nodelet/releases/download/v0.2.8/nodelet-0.2.8-15.x86_64.deb
- https://github.com/platform9/nodelet/releases/download/v0.2.8/nodelet-0.2.8-15.x86_64.deb.md5
- https://github.com/platform9/nodelet/releases/download/v0.2.8/nodelet-0.2.8-15.x86_64.rpm
- https://github.com/platform9/nodelet/releases/download/v0.2.8/nodelet-0.2.8-15.x86_64.rpm.md5
- https://github.com/platform9/nodelet/releases/download/v0.2.8/nodeletctl

Preferred state
- https://github.com/platform9/nodelet/releases/download/v0.2.8/nodelet-v0.2.8.x86_64.deb
- https://github.com/platform9/nodelet/releases/download/v0.2.8/nodelet-v0.2.8.x86_64.deb.md5
- https://github.com/platform9/nodelet/releases/download/v0.2.8/nodelet-v0.2.8.x86_64.rpm
- https://github.com/platform9/nodelet/releases/download/v0.2.8/nodelet-v0.2.8.x86_64.rpm.md5
- https://github.com/platform9/nodelet/releases/download/v0.2.8/nodeletctl

The preferred state would allow me to programmatically define the release url in an Ansible Jinja2 template:

```yaml
nodelet_release:
  version: v0.2.8
  package: deb
  package_url: https://github.com/platform9/nodelet/releases/download/{{ nodelet_release.version }}/nodelet-{{ nodelet_release.version }}.x86_64.{{ nodelet_release.package }}
  package_md5_url: https://github.com/platform9/nodelet/releases/download/{{ nodelet_release.version }}/nodelet-{{ nodelet_release.version }}.x86_64.{{ nodelet_release.package }}.md5
  cli_url: https://github.com/platform9/nodelet/releases/download/{{ nodelet_release.version }}/nodeletctl
```
